### ISSUE TITLE
クライアントが反則勝ちできてしまう

### ISSUE THREAD

**Issue by Kurorororo** [mak4026/submarine_game#18]
```
waiting
{"moved"=>false}
{"me"=>{"w"=>{"hp"=>3, "position"=>[3, 0]}}, "enemy"=>{"w"=>{"hp"=>2}, "c"=>{"hp"=>2}, "s"=>{"hp"=>1}}}
players/ai_player_simple.rb:110:in `update': undefined method `[]' for false:FalseClass (NoMethodError)
    from players/ai_player_simple.rb:138:in `block in main'
    from players/ai_player_simple.rb:131:in `loop'
    from players/ai_player_simple.rb:131:in `main'
    from players/ai_player_simple.rb:152:in `<main>'
```

どうも行動結果のJSONに不正な値を入れられると死んでしまうよう

**Comment by Kurorororo** [comment]
ai_player_nozawaから送られてきたJSONを履かせてみると

```
"{\"move\":{\"ship\":\"w\",\"to\":[-1,0]}}\n"
```

負の座標を指定されている。
