### ISSUE TITLE
manual_playerで存在しない艦を移動させようとするとエラーが出る

### ISSUE THREAD

**Issue by Kurorororo** [mak4026/submarine_game#24]
```
please input "w" or "c" or "s"
select your ship: c
x = 3
y = 0
players/manual_player.rb:34:in `action': undefined method `reachable?' for nil:NilClass (NoMethodError)
    from players/manual_player.rb:230:in `block in main'
    from players/manual_player.rb:225:in `loop'
    from players/manual_player.rb:225:in `main'
    from players/manual_player.rb:249:in `<main>'
```

**Comment by Kurorororo** [comment]
間違えてmasterにpushしちゃったけど修正済み
